### ISSUE TITLE
Error after updating Extension

### ISSUE THREAD

**Issue by toniocus** [Favo02/workspaces-by-open-apps#49] opened 2023-10-26 12:51 UTC
Using Fedora 38,  Gnome 44

After updating to the last version, I'm getting ab error when I try to open configuration,
the extensions seems to start but not "honoring" configuration.

I'm copying the details that the config shows, any other thing I can inform you please let
me know.

Thanks in advance.
Tonio

Here the details:
==========================================================================

The settings of extension workspaces-by-open-apps@favo02.github.com had an error:

```
Error: Wrong type number; string expected
```

Stack trace:
```
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
about_page@/home/tonioc/.local/share/gnome-shell/extensions/workspaces-by-open-apps@favo02.github.com/prefs.js:488:12
fillPreferencesWindow@/home/tonioc/.local/share/gnome-shell/extensions/workspaces-by-open-apps@favo02.github.com/prefs.js:68:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by agitate** [comment] 2023-10-26 18:45
Looks like it is caused by the application version being a number, not a string, and the constructor for Gtk.Label requiring a string as the first parameter. You can see the code in prefs.js on line 489, although the code in the repo looks to have been refactored since the release of version 9, so presumably another release with a fix is on the way. If you want to just hack the extension to get it to work for now, you can edit this file:

~/.local/share/gnome-shell/extensions/workspaces-by-open-apps@favo02.github.com/prefs.js

And change line 489 to:

    `label: String(Me.metadata.version),`

**Comment by toniocus** [comment] 2023-10-26 18:49
great thanks, I'll change in the meanwhile.

**Comment by Favo02** [comment] 2023-10-26 20:02
Thanks for the report!

The weird thing is that it didn't cause any issue on my local machine, running the same environment (Fedora 38, GNOME 44). I am going to release an hotfix as soon as possible (it will take some time before it gets reviewed an published).

I will close this issue as soon as it gets accepted the new version.

**Closed** 2023-10-27 20:32 UTC
Labels: fix, GNOME 40-44

**Comment by toniocus** [comment] 2023-10-28 15:24
Hey @Favo02 ,  the  update just arrived and everything is working perfectly well !!!!!

Wasn't expecting it to come so quickly.
Thanks a lot, :-)
